import { Rosarivo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import AnimatedCursor from "react-animated-cursor";
import HeroSection from "./components/HeroSection";

const rosarivo = Rosarivo({
  weight: ["400"],
  variable: "--font-rosarivo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rosarivo.className}>
        <div className="hidden lg:block">
          <AnimatedCursor
            innerSize={8}
            outerSize={24}
            color="var(--foreground)"
            outerAlpha={0.6}
            innerScale={1.2}
            outerScale={2.8}
            trailingSpeed={8}
            showSystemCursor={false}
            hasBlendMode={false}
            clickables={[
              "a",
              'input[type="text"]',
              'input[type="email"]',
              'input[type="number"]',
              'input[type="submit"]',
              'input[type="image"]',
              "label[for]",
              "select",
              "textarea",
              "button",
              ".link",
              ".cursor-pointer",
              ".card",
              ".hover-target",
              "img",
              "video",
            ]}
            outerStyle={{
              border: "2px solid var(--foreground)",
              borderRadius: "50%",
              backdropFilter: "blur(4px)",
              opacity: 0.6,
            }}
            innerStyle={{
              backgroundColor: "var(--foreground)",
              borderRadius: "50%",
              boxShadow: "0 0 8px var(--foreground)",
              opacity: 0.8,
            }}
          />
        </div>
        <Navbar />
      
        {children}
      </body>
    </html>
  );
}
